name: Check Dependabot Alerts

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check_dependabot_alerts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install gh jq

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.PERSONAL_ACCESS_TOKEN }}" | gh auth login --with-token

      - name: Fetch Dependabot Alerts
        id: fetch_alerts
        run: |
          # Fetch Dependabot alerts using GitHub CLI
          response=$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/dependabot/alerts)

          # Count the number of alerts
          alert_count=$(echo "$response" | jq '. | length')
          
          # Set the alert count as an output
          echo "ALERT_COUNT=$alert_count" >> $GITHUB_ENV

      - name: Check if PR is from Dependabot
        id: check-dependabot
        run: |
          if [[ "${{ github.actor }}" == "dependabot[bot]" ]]; then
            echo "Dependabot PR detected"
            echo "notify=true" >> $GITHUB_ENV
          else
            echo "No notification"
            echo "notify=false" >> $GITHUB_ENV
          fi

      - name: Send Slack Notification For Dependabot PR
        if: env.notify == 'true'
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data "{\"text\":\"A new PR has been created or updated by Dependabot: ${{ github.event.pull_request.html_url }}\"}" \
          ${{ secrets.SLACK_WEBHOOK }}
          
      - name: Notify on Slack for Vulnerabilites
        if: ${{ env.ALERT_COUNT > 0 }}
        
        uses: kunalnagarco/action-cve@v1.7.15
        
        with:

          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # This secret need to be created

          slack_webhook: ${{ secrets.SLACK_WEBHOOK }} # This secret need to be created
